# Jekyll Resume Theme

# Site settings
title: Sameer Sadiq
email: sameersadiq1@gmail.com
description:
baseurl:
url:
url:
name: Sameer Sadiq
job: Automation Engineer
location: Indianapolis, IN
languages: Selenium, Ruby, Java, Cucumber, Gherkin, Jmeter, SOAP UI, Jenkins, Jira and more.
twitter_username: sameersadiq1
github_username:  sameersadiq1
email_address: sameersadiq1@gmail.com

# Build settings
markdown: kramdown
