# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sameer Sadiq
email: sameersadiq1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  HI! Welcome to my website. My name is Sameer Sadiq. Please feel free to contact me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "sameersadiq1@gmail.com" # the base hostname & protocol for your site
twitter_username: sameersadiq1
github_username:  sameersadiq1

# Build settings
markdown: kramdown
